bbs/max_range: 15.0

bbs/min_tx: -500.0
bbs/max_tx: 230.0
bbs/min_ty: -370.0
bbs/max_ty: 50.0

bbs/min_theta: -3.15
bbs/max_theta: 3.15

# global map config
# slice height range (map coordinate)
bbs/map_min_z: 2.0
bbs/map_max_z: 2.4

# 2D map params
bbs/map_width: 2000
bbs/map_height: 1500


bbs/map_resolution: 1.0
bbs/max_points_per_cell: 5 #5
# precomp map pyramid
bbs/map_pyramid_level: 6

# bbs/scan_min_z: 3.5
bbs/scan_min_z: 3.0

bbs/scan_max_z: 3.4
